---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: bilorge/karoo:latest
    image: amazonlinux
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
