---
molecule:
  ignore_paths:
    - lib
    - bin
    - library
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: karoo
    image: amazonlinux  
# docker:
#   containers:
#     - name: docker
#       # image: centos/systemd
#       image: amazonlinux
#       image_version: latest
#       privileged: True
#       ansible_groups:
#         - docker
verifier:
  name: ansible
  provisioner:
    name: ansible
